//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Zapasnojj_postamat
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Запись получ.
    /// </summary>
    // *** Start programmer edit section *** (ЗаписьПолуч CustomAttributes)

    // *** End programmer edit section *** (ЗаписьПолуч CustomAttributes)
    [AutoAltered()]
    [Caption("Запись получ")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаписьПолучE", new string[] {
            "ДатаПолуч as \'Дата получения\'",
            "ВремяПолуч as \'Время получения\'",
            "Ячейка as \'Ячейка\'",
            "Ячейка.НомерЯчейки as \'Номер ячейки\'",
            "Посылка as \'Посылка\'",
            "Посылка.НомПосылки as \'Номер посылки\'"}, Hidden=new string[] {
            "Ячейка.НомерЯчейки",
            "Посылка.НомПосылки"})]
    [MasterViewDefineAttribute("ЗаписьПолучE", "Ячейка", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерЯчейки")]
    [MasterViewDefineAttribute("ЗаписьПолучE", "Посылка", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомПосылки")]
    public class ЗаписьПолуч : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаПолуч = System.DateTime.Now;
        
        private string fВремяПолуч;
        
        private IIS.Zapasnojj_postamat.Ячейка fЯчейка;
        
        private IIS.Zapasnojj_postamat.Посылка fПосылка;
        
        private IIS.Zapasnojj_postamat.Постамат fПостамат;
        
        // *** Start programmer edit section *** (ЗаписьПолуч CustomMembers)

        // *** End programmer edit section *** (ЗаписьПолуч CustomMembers)

        
        /// <summary>
        /// ВремяПолуч.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьПолуч.ВремяПолуч CustomAttributes)

        // *** End programmer edit section *** (ЗаписьПолуч.ВремяПолуч CustomAttributes)
        [StrLen(255)]
        public virtual string ВремяПолуч
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьПолуч.ВремяПолуч Get start)

                // *** End programmer edit section *** (ЗаписьПолуч.ВремяПолуч Get start)
                string result = this.fВремяПолуч;
                // *** Start programmer edit section *** (ЗаписьПолуч.ВремяПолуч Get end)

                // *** End programmer edit section *** (ЗаписьПолуч.ВремяПолуч Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьПолуч.ВремяПолуч Set start)

                // *** End programmer edit section *** (ЗаписьПолуч.ВремяПолуч Set start)
                this.fВремяПолуч = value;
                // *** Start programmer edit section *** (ЗаписьПолуч.ВремяПолуч Set end)

                // *** End programmer edit section *** (ЗаписьПолуч.ВремяПолуч Set end)
            }
        }
        
        /// <summary>
        /// ДатаПолуч.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьПолуч.ДатаПолуч CustomAttributes)

        // *** End programmer edit section *** (ЗаписьПолуч.ДатаПолуч CustomAttributes)
        public virtual System.DateTime ДатаПолуч
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьПолуч.ДатаПолуч Get start)

                // *** End programmer edit section *** (ЗаписьПолуч.ДатаПолуч Get start)
                System.DateTime result = this.fДатаПолуч;
                // *** Start programmer edit section *** (ЗаписьПолуч.ДатаПолуч Get end)

                // *** End programmer edit section *** (ЗаписьПолуч.ДатаПолуч Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьПолуч.ДатаПолуч Set start)

                // *** End programmer edit section *** (ЗаписьПолуч.ДатаПолуч Set start)
                this.fДатаПолуч = value;
                // *** Start programmer edit section *** (ЗаписьПолуч.ДатаПолуч Set end)

                // *** End programmer edit section *** (ЗаписьПолуч.ДатаПолуч Set end)
            }
        }
        
        /// <summary>
        /// Запись получ.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьПолуч.Посылка CustomAttributes)

        // *** End programmer edit section *** (ЗаписьПолуч.Посылка CustomAttributes)
        [PropertyStorage(new string[] {
                "Посылка"})]
        [NotNull()]
        public virtual IIS.Zapasnojj_postamat.Посылка Посылка
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьПолуч.Посылка Get start)

                // *** End programmer edit section *** (ЗаписьПолуч.Посылка Get start)
                IIS.Zapasnojj_postamat.Посылка result = this.fПосылка;
                // *** Start programmer edit section *** (ЗаписьПолуч.Посылка Get end)

                // *** End programmer edit section *** (ЗаписьПолуч.Посылка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьПолуч.Посылка Set start)

                // *** End programmer edit section *** (ЗаписьПолуч.Посылка Set start)
                this.fПосылка = value;
                // *** Start programmer edit section *** (ЗаписьПолуч.Посылка Set end)

                // *** End programmer edit section *** (ЗаписьПолуч.Посылка Set end)
            }
        }
        
        /// <summary>
        /// Запись получ.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьПолуч.Ячейка CustomAttributes)

        // *** End programmer edit section *** (ЗаписьПолуч.Ячейка CustomAttributes)
        [PropertyStorage(new string[] {
                "Ячейка"})]
        [NotNull()]
        public virtual IIS.Zapasnojj_postamat.Ячейка Ячейка
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьПолуч.Ячейка Get start)

                // *** End programmer edit section *** (ЗаписьПолуч.Ячейка Get start)
                IIS.Zapasnojj_postamat.Ячейка result = this.fЯчейка;
                // *** Start programmer edit section *** (ЗаписьПолуч.Ячейка Get end)

                // *** End programmer edit section *** (ЗаписьПолуч.Ячейка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьПолуч.Ячейка Set start)

                // *** End programmer edit section *** (ЗаписьПолуч.Ячейка Set start)
                this.fЯчейка = value;
                // *** Start programmer edit section *** (ЗаписьПолуч.Ячейка Set end)

                // *** End programmer edit section *** (ЗаписьПолуч.Ячейка Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Zapasnojj_postamat.Постамат.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьПолуч.Постамат CustomAttributes)

        // *** End programmer edit section *** (ЗаписьПолуч.Постамат CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Постамат"})]
        public virtual IIS.Zapasnojj_postamat.Постамат Постамат
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьПолуч.Постамат Get start)

                // *** End programmer edit section *** (ЗаписьПолуч.Постамат Get start)
                IIS.Zapasnojj_postamat.Постамат result = this.fПостамат;
                // *** Start programmer edit section *** (ЗаписьПолуч.Постамат Get end)

                // *** End programmer edit section *** (ЗаписьПолуч.Постамат Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьПолуч.Постамат Set start)

                // *** End programmer edit section *** (ЗаписьПолуч.Постамат Set start)
                this.fПостамат = value;
                // *** Start programmer edit section *** (ЗаписьПолуч.Постамат Set end)

                // *** End programmer edit section *** (ЗаписьПолуч.Постамат Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаписьПолучE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаписьПолучE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаписьПолучE", typeof(IIS.Zapasnojj_postamat.ЗаписьПолуч));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ЗаписьПолуч.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfЗаписьПолуч CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfЗаписьПолуч CustomAttributes)
    public class DetailArrayOfЗаписьПолуч : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Zapasnojj_postamat.DetailArrayOfЗаписьПолуч members)

        // *** End programmer edit section *** (IIS.Zapasnojj_postamat.DetailArrayOfЗаписьПолуч members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ЗаписьПолуч by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ЗаписьПолуч.
        /// </summary>
        public DetailArrayOfЗаписьПолуч(IIS.Zapasnojj_postamat.Постамат fПостамат) : 
                base(typeof(ЗаписьПолуч), ((ICSSoft.STORMNET.DataObject)(fПостамат)))
        {
        }
        
        public IIS.Zapasnojj_postamat.ЗаписьПолуч this[int index]
        {
            get
            {
                return ((IIS.Zapasnojj_postamat.ЗаписьПолуч)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Zapasnojj_postamat.ЗаписьПолуч dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
