//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Zapasnojj_postamat
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Получатель.
    /// </summary>
    // *** Start programmer edit section *** (Получатель CustomAttributes)

    // *** End programmer edit section *** (Получатель CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПолучательE", new string[] {
            "ФИО as \'ФИО\'",
            "Телефон as \'Телефон\'"})]
    [View("ПолучательL", new string[] {
            "ФИО as \'ФИО\'",
            "Телефон as \'Телефон\'"})]
    public class Получатель : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private int fТелефон;
        
        // *** Start programmer edit section *** (Получатель CustomMembers)

        // *** End programmer edit section *** (Получатель CustomMembers)

        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (Получатель.Телефон CustomAttributes)

        // *** End programmer edit section *** (Получатель.Телефон CustomAttributes)
        public virtual int Телефон
        {
            get
            {
                // *** Start programmer edit section *** (Получатель.Телефон Get start)

                // *** End programmer edit section *** (Получатель.Телефон Get start)
                int result = this.fТелефон;
                // *** Start programmer edit section *** (Получатель.Телефон Get end)

                // *** End programmer edit section *** (Получатель.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Получатель.Телефон Set start)

                // *** End programmer edit section *** (Получатель.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (Получатель.Телефон Set end)

                // *** End programmer edit section *** (Получатель.Телефон Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Получатель.ФИО CustomAttributes)

        // *** End programmer edit section *** (Получатель.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Получатель.ФИО Get start)

                // *** End programmer edit section *** (Получатель.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Получатель.ФИО Get end)

                // *** End programmer edit section *** (Получатель.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Получатель.ФИО Set start)

                // *** End programmer edit section *** (Получатель.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Получатель.ФИО Set end)

                // *** End programmer edit section *** (Получатель.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПолучательE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПолучательE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПолучательE", typeof(IIS.Zapasnojj_postamat.Получатель));
                }
            }
            
            /// <summary>
            /// "ПолучательL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПолучательL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПолучательL", typeof(IIS.Zapasnojj_postamat.Получатель));
                }
            }
        }
    }
}
