//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Zapasnojj_postamat
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Посылка.
    /// </summary>
    // *** Start programmer edit section *** (Посылка CustomAttributes)

    // *** End programmer edit section *** (Посылка CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПосылкаE", new string[] {
            "НомПосылки as \'Номер посылки\'",
            "Статус as \'Статус\'",
            "НомерПост as \'Номер постамата\'",
            "НомерЯчейки as \'Номер ячейки\'",
            "Получатель as \'Получатель\'",
            "Получатель.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Получатель.ФИО"})]
    [MasterViewDefineAttribute("ПосылкаE", "Получатель", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ПосылкаL", new string[] {
            "НомПосылки as \'Ном посылки\'",
            "Статус as \'Статус\'",
            "НомерПост as \'Номер постамата\'",
            "НомерЯчейки as \'Номер ячейки\'",
            "Получатель.ФИО as \'ФИО\'"})]
    public class Посылка : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомПосылки;
        
        private IIS.Zapasnojj_postamat.Статусы fСтатус;
        
        private int fНомерПост;
        
        private int fНомерЯчейки;
        
        private IIS.Zapasnojj_postamat.Получатель fПолучатель;
        
        // *** Start programmer edit section *** (Посылка CustomMembers)

        // *** End programmer edit section *** (Посылка CustomMembers)

        
        /// <summary>
        /// НомерПост.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.НомерПост CustomAttributes)

        // *** End programmer edit section *** (Посылка.НомерПост CustomAttributes)
        public virtual int НомерПост
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.НомерПост Get start)

                // *** End programmer edit section *** (Посылка.НомерПост Get start)
                int result = this.fНомерПост;
                // *** Start programmer edit section *** (Посылка.НомерПост Get end)

                // *** End programmer edit section *** (Посылка.НомерПост Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.НомерПост Set start)

                // *** End programmer edit section *** (Посылка.НомерПост Set start)
                this.fНомерПост = value;
                // *** Start programmer edit section *** (Посылка.НомерПост Set end)

                // *** End programmer edit section *** (Посылка.НомерПост Set end)
            }
        }
        
        /// <summary>
        /// НомерЯчейки.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.НомерЯчейки CustomAttributes)

        // *** End programmer edit section *** (Посылка.НомерЯчейки CustomAttributes)
        public virtual int НомерЯчейки
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.НомерЯчейки Get start)

                // *** End programmer edit section *** (Посылка.НомерЯчейки Get start)
                int result = this.fНомерЯчейки;
                // *** Start programmer edit section *** (Посылка.НомерЯчейки Get end)

                // *** End programmer edit section *** (Посылка.НомерЯчейки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.НомерЯчейки Set start)

                // *** End programmer edit section *** (Посылка.НомерЯчейки Set start)
                this.fНомерЯчейки = value;
                // *** Start programmer edit section *** (Посылка.НомерЯчейки Set end)

                // *** End programmer edit section *** (Посылка.НомерЯчейки Set end)
            }
        }
        
        /// <summary>
        /// НомПосылки.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.НомПосылки CustomAttributes)

        // *** End programmer edit section *** (Посылка.НомПосылки CustomAttributes)
        public virtual int НомПосылки
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.НомПосылки Get start)

                // *** End programmer edit section *** (Посылка.НомПосылки Get start)
                int result = this.fНомПосылки;
                // *** Start programmer edit section *** (Посылка.НомПосылки Get end)

                // *** End programmer edit section *** (Посылка.НомПосылки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.НомПосылки Set start)

                // *** End programmer edit section *** (Посылка.НомПосылки Set start)
                this.fНомПосылки = value;
                // *** Start programmer edit section *** (Посылка.НомПосылки Set end)

                // *** End programmer edit section *** (Посылка.НомПосылки Set end)
            }
        }
        
        /// <summary>
        /// Статус.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.Статус CustomAttributes)

        // *** End programmer edit section *** (Посылка.Статус CustomAttributes)
        public virtual IIS.Zapasnojj_postamat.Статусы Статус
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.Статус Get start)

                // *** End programmer edit section *** (Посылка.Статус Get start)
                IIS.Zapasnojj_postamat.Статусы result = this.fСтатус;
                // *** Start programmer edit section *** (Посылка.Статус Get end)

                // *** End programmer edit section *** (Посылка.Статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.Статус Set start)

                // *** End programmer edit section *** (Посылка.Статус Set start)
                this.fСтатус = value;
                // *** Start programmer edit section *** (Посылка.Статус Set end)

                // *** End programmer edit section *** (Посылка.Статус Set end)
            }
        }
        
        /// <summary>
        /// Посылка.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.Получатель CustomAttributes)

        // *** End programmer edit section *** (Посылка.Получатель CustomAttributes)
        [PropertyStorage(new string[] {
                "Получатель"})]
        [NotNull()]
        public virtual IIS.Zapasnojj_postamat.Получатель Получатель
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.Получатель Get start)

                // *** End programmer edit section *** (Посылка.Получатель Get start)
                IIS.Zapasnojj_postamat.Получатель result = this.fПолучатель;
                // *** Start programmer edit section *** (Посылка.Получатель Get end)

                // *** End programmer edit section *** (Посылка.Получатель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.Получатель Set start)

                // *** End programmer edit section *** (Посылка.Получатель Set start)
                this.fПолучатель = value;
                // *** Start programmer edit section *** (Посылка.Получатель Set end)

                // *** End programmer edit section *** (Посылка.Получатель Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПосылкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПосылкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПосылкаE", typeof(IIS.Zapasnojj_postamat.Посылка));
                }
            }
            
            /// <summary>
            /// "ПосылкаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПосылкаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПосылкаL", typeof(IIS.Zapasnojj_postamat.Посылка));
                }
            }
        }
    }
}
