//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Zapasnojj_postamat
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Постамат.
    /// </summary>
    // *** Start programmer edit section *** (Постамат CustomAttributes)

    // *** End programmer edit section *** (Постамат CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПостаматE", new string[] {
            "НомерПост as \'Номер постамата\'",
            "Адрес as \'Адрес\'"})]
    [AssociatedDetailViewAttribute("ПостаматE", "ЗаписьПолуч", "ЗаписьПолучE", true, "", "Запись о получении", true, new string[] {
            ""})]
    public class Постамат : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерПост;
        
        private string fАдрес;
        
        private IIS.Zapasnojj_postamat.DetailArrayOfЗаписьПолуч fЗаписьПолуч;
        
        private IIS.Zapasnojj_postamat.Точка fТочка;
        
        // *** Start programmer edit section *** (Постамат CustomMembers)

        // *** End programmer edit section *** (Постамат CustomMembers)

        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (Постамат.Адрес CustomAttributes)

        // *** End programmer edit section *** (Постамат.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Постамат.Адрес Get start)

                // *** End programmer edit section *** (Постамат.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (Постамат.Адрес Get end)

                // *** End programmer edit section *** (Постамат.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Постамат.Адрес Set start)

                // *** End programmer edit section *** (Постамат.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Постамат.Адрес Set end)

                // *** End programmer edit section *** (Постамат.Адрес Set end)
            }
        }
        
        /// <summary>
        /// НомерПост.
        /// </summary>
        // *** Start programmer edit section *** (Постамат.НомерПост CustomAttributes)

        // *** End programmer edit section *** (Постамат.НомерПост CustomAttributes)
        public virtual int НомерПост
        {
            get
            {
                // *** Start programmer edit section *** (Постамат.НомерПост Get start)

                // *** End programmer edit section *** (Постамат.НомерПост Get start)
                int result = this.fНомерПост;
                // *** Start programmer edit section *** (Постамат.НомерПост Get end)

                // *** End programmer edit section *** (Постамат.НомерПост Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Постамат.НомерПост Set start)

                // *** End programmer edit section *** (Постамат.НомерПост Set start)
                this.fНомерПост = value;
                // *** Start programmer edit section *** (Постамат.НомерПост Set end)

                // *** End programmer edit section *** (Постамат.НомерПост Set end)
            }
        }
        
        /// <summary>
        /// Постамат.
        /// </summary>
        // *** Start programmer edit section *** (Постамат.ЗаписьПолуч CustomAttributes)

        // *** End programmer edit section *** (Постамат.ЗаписьПолуч CustomAttributes)
        public virtual IIS.Zapasnojj_postamat.DetailArrayOfЗаписьПолуч ЗаписьПолуч
        {
            get
            {
                // *** Start programmer edit section *** (Постамат.ЗаписьПолуч Get start)

                // *** End programmer edit section *** (Постамат.ЗаписьПолуч Get start)
                if ((this.fЗаписьПолуч == null))
                {
                    this.fЗаписьПолуч = new IIS.Zapasnojj_postamat.DetailArrayOfЗаписьПолуч(this);
                }
                IIS.Zapasnojj_postamat.DetailArrayOfЗаписьПолуч result = this.fЗаписьПолуч;
                // *** Start programmer edit section *** (Постамат.ЗаписьПолуч Get end)

                // *** End programmer edit section *** (Постамат.ЗаписьПолуч Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Постамат.ЗаписьПолуч Set start)

                // *** End programmer edit section *** (Постамат.ЗаписьПолуч Set start)
                this.fЗаписьПолуч = value;
                // *** Start programmer edit section *** (Постамат.ЗаписьПолуч Set end)

                // *** End programmer edit section *** (Постамат.ЗаписьПолуч Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Zapasnojj_postamat.Точка.
        /// </summary>
        // *** Start programmer edit section *** (Постамат.Точка CustomAttributes)

        // *** End programmer edit section *** (Постамат.Точка CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Точка"})]
        public virtual IIS.Zapasnojj_postamat.Точка Точка
        {
            get
            {
                // *** Start programmer edit section *** (Постамат.Точка Get start)

                // *** End programmer edit section *** (Постамат.Точка Get start)
                IIS.Zapasnojj_postamat.Точка result = this.fТочка;
                // *** Start programmer edit section *** (Постамат.Точка Get end)

                // *** End programmer edit section *** (Постамат.Точка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Постамат.Точка Set start)

                // *** End programmer edit section *** (Постамат.Точка Set start)
                this.fТочка = value;
                // *** Start programmer edit section *** (Постамат.Точка Set end)

                // *** End programmer edit section *** (Постамат.Точка Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПостаматE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПостаматE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПостаматE", typeof(IIS.Zapasnojj_postamat.Постамат));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Постамат.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfПостамат CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfПостамат CustomAttributes)
    public class DetailArrayOfПостамат : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Zapasnojj_postamat.DetailArrayOfПостамат members)

        // *** End programmer edit section *** (IIS.Zapasnojj_postamat.DetailArrayOfПостамат members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Постамат by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Постамат.
        /// </summary>
        public DetailArrayOfПостамат(IIS.Zapasnojj_postamat.Точка fТочка) : 
                base(typeof(Постамат), ((ICSSoft.STORMNET.DataObject)(fТочка)))
        {
        }
        
        public IIS.Zapasnojj_postamat.Постамат this[int index]
        {
            get
            {
                return ((IIS.Zapasnojj_postamat.Постамат)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Zapasnojj_postamat.Постамат dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
