//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Zapasnojj_postamat
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Статус ячейк.
    /// </summary>
    // *** Start programmer edit section *** (СтатусЯчейк CustomAttributes)

    // *** End programmer edit section *** (СтатусЯчейк CustomAttributes)
    public enum СтатусЯчейк
    {
        
        // *** Start programmer edit section *** (СтатусЯчейк.1 CustomAttributes)

        // *** End programmer edit section *** (СтатусЯчейк.1 CustomAttributes)
        [Caption("Занята")]
        1,
        
        // *** Start programmer edit section *** (СтатусЯчейк.2 CustomAttributes)

        // *** End programmer edit section *** (СтатусЯчейк.2 CustomAttributes)
        [Caption("Свободна")]
        2,
    }
}
