//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Zapasnojj_postamat
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Точка.
    /// </summary>
    // *** Start programmer edit section *** (Точка CustomAttributes)

    // *** End programmer edit section *** (Точка CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТочкаE", new string[] {
            "Адрес as \'Адрес\'"})]
    [AssociatedDetailViewAttribute("ТочкаE", "Постамат", "ПостаматE", true, "", "Постамат", true, new string[] {
            ""})]
    [View("ТочкаL", new string[] {
            "Адрес as \'Адрес\'"})]
    public class Точка : ICSSoft.STORMNET.DataObject
    {
        
        private string fАдрес;
        
        private IIS.Zapasnojj_postamat.DetailArrayOfПостамат fПостамат;
        
        // *** Start programmer edit section *** (Точка CustomMembers)

        // *** End programmer edit section *** (Точка CustomMembers)

        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (Точка.Адрес CustomAttributes)

        // *** End programmer edit section *** (Точка.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Точка.Адрес Get start)

                // *** End programmer edit section *** (Точка.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (Точка.Адрес Get end)

                // *** End programmer edit section *** (Точка.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Точка.Адрес Set start)

                // *** End programmer edit section *** (Точка.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Точка.Адрес Set end)

                // *** End programmer edit section *** (Точка.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Точка.
        /// </summary>
        // *** Start programmer edit section *** (Точка.Постамат CustomAttributes)

        // *** End programmer edit section *** (Точка.Постамат CustomAttributes)
        public virtual IIS.Zapasnojj_postamat.DetailArrayOfПостамат Постамат
        {
            get
            {
                // *** Start programmer edit section *** (Точка.Постамат Get start)

                // *** End programmer edit section *** (Точка.Постамат Get start)
                if ((this.fПостамат == null))
                {
                    this.fПостамат = new IIS.Zapasnojj_postamat.DetailArrayOfПостамат(this);
                }
                IIS.Zapasnojj_postamat.DetailArrayOfПостамат result = this.fПостамат;
                // *** Start programmer edit section *** (Точка.Постамат Get end)

                // *** End programmer edit section *** (Точка.Постамат Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Точка.Постамат Set start)

                // *** End programmer edit section *** (Точка.Постамат Set start)
                this.fПостамат = value;
                // *** Start programmer edit section *** (Точка.Постамат Set end)

                // *** End programmer edit section *** (Точка.Постамат Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТочкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТочкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТочкаE", typeof(IIS.Zapasnojj_postamat.Точка));
                }
            }
            
            /// <summary>
            /// "ТочкаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТочкаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТочкаL", typeof(IIS.Zapasnojj_postamat.Точка));
                }
            }
        }
    }
}
